
steps:
- name: backend
  image: golang:1.14.2
  commands:
  - echo "look at this, it's awesome"
  - go version

- name: frontend
  image: busybox
  commands:
  - pwd
  - ls
  - cat test.txt
  - echo hello
  - sleep 30
  - echo world

- name: terza
  image: busybox
  commands:
  - echo daje 3
